# Generated by Django 3.0.3 on 2020-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('war_and_peace', models.IntegerField()),
                ('immigration', models.IntegerField()),
                ('gun_control', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('drugs', models.IntegerField()),
                ('civil_rights', models.IntegerField()),
                ('jobs', models.IntegerField()),
                ('environment', models.IntegerField()),
                ('budget_and_economy', models.IntegerField()),
                ('tax_reform', models.IntegerField()),
                ('social_security', models.IntegerField()),
                ('infrastructure', models.IntegerField()),
                ('education', models.IntegerField()),
                ('healthcare', models.IntegerField()),
                ('abortion', models.IntegerField()),
            ],
        ),
    ]
